version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      - image: circleci/node:14-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run tests
          command: yarn test-ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./junit
            JEST_JUNIT_OUTPUT_NAME: test-results.xml
      - codecov/upload:
          file: ./coverage/lcov.info
      - store_artifacts:
          path: ./coverage
      - store_test_results:
          path: ./junit
